CREATE DATABASE IF NOT EXISTS PULSE_GRID;
USE PULSE_GRID;

CREATE TABLE IF NOT EXISTs USERS(
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(40) UNIQUE NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    profile_picture TEXT NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    passwordHash VARCHAR(100) NOT NULL,
    role ENUM('player','admin') NOT NULL DEFAULT 'player',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_username (username),
    INDEX idx_email (email)
);

CREATE TABLE IF NOT EXISTS GAMES(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    logo TEXT NOT NULL,
    genre VARCHAR(50),
    max_players_per_team INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TEAMS(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(80) NOT NULL,
    tag VARCHAR(6) UNIQUE NOT NULL,
    logo TEXT,
    description TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TOURNAMENTS(
    id INT PRIMARY KEY AUTO_INCREMENT,
    game_id INT NOT NULL,
    name VARCHAR(120) NOT NULL,
    format ENUM('single_elimination','double_elimination','round_robin') NOT NULL,
    max_teams INT NOT NULL,
    registration_deadline DATETIME NOT NULL,
    startsAt DATETIME NOT NULL,
    prize_pool DECIMAL(10,2),
    status ENUM('upcoming','active','completed','cancelled') NOT NULL DEFAULT 'upcoming',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (game_id) REFERENCES GAMES(id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS MATCHES(
    id INT PRIMARY KEY AUTO_INCREMENT,
    tournament_id INT NOT NULL,
    team1_id INT,
    team2_id INT,
    winner_id INT,
    score VARCHAR(20) DEFAULT '0:0',
    round INT NOT NULL,
    status ENUM('scheduled', 'ongoing', 'completed') NOT NULL DEFAULT 'scheduled',
    scheduled DATETIME,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (tournament_id) REFERENCES TOURNAMENTS(id) ON DELETE CASCADE,
    FOREIGN KEY (team1_id) REFERENCES TEAMS(id) ON DELETE SET NULL,
    FOREIGN KEY (team2_id) REFERENCES TEAMS(id) ON DELETE SET NULL,
    FOREIGN KEY (winner_id) REFERENCES TEAMS(id) ON DELETE SET NULL 
);